import React from 'react';

const index = () => {
  return (
    <div className='mt-[100px]'>
      <div className='header-section mb-[250px]'>
        <div className=' bg-[#009E60] py-[50px]'>
          <div className='mx-[180px]'>
            <h1 className='text-[44px] font-semibold text-[#000000d9]'>
              Privacy Policy
            </h1>
            <div className='w-24 border-b-2 border-green-400' />
          </div>
        </div>

        <div className='container mx-auto mt-[15px]'>
          <div className='section-header'>
            <h2 className='text-[24px] text-[#2d3748]'>
              OHM Platform Privacy Policy
            </h2>
            <div className='w-24 border-b-2 border-green-400' />
          </div>
          <div className='bold-section p-2'>
            <p className='font-sans text-[16px] font-medium text-gray-800'>
              This document is an electronic record in terms of Information
              Technology Act, 2000 and rules there under as applicable and the
              amended provisions pertaining to electronic records in various
              statutes as amended by the Information Technology Act, 2000. This
              electronic record is generated by a computer system and does not
              require any physical or digital signatures. This document is
              published in accordance with the provisions of Rule 3 (1) of the
              Information Technology (Intermediaries guidelines) Rules, 2011
              that require publishing the rules and regulations, privacy policy
              and Terms of Use for access or usage of www.OHM.com website.
            </p>
          </div>
          <div className='paragraph-section-1 p-2'>
            <p>
              The domain name www.OHM.com and its sub-domains,
              internet-based/electronic applications, mobile applications,
              including its portals, OHM App (hereinafter collectively referred
              to as the “OHM Platform”, “Website”) is owned by Trafinserve
              Private Limited, a company incorporated under the laws of the
              Republic of India having its registered address at BP-137(west),
              Shalimar Bagh, New Delhi-110088.
            </p>
          </div>
          <div className='paragraph-section-2 p-2'>
            <p>
              OHM Platform has adopted this OHM Platform Service Recipient Terms
              of Use (“SRTOU” or Terms).
            </p>
          </div>
          <div className='paragraph-section-3 p-2'>
            <p>
              You are informed that the terms herein govern Service Recipient
              User Account(“SRUA” or “User Account”) on the OHM Platform and its
              use.
            </p>
          </div>
          <div className='section-header'>
            <h2 className='font-roboto text-[20px] text-gray-800'>
              Definitions
            </h2>
          </div>
          <div className='paragraph mt-[10px] mb-[10px] items-center px-2'>
            <span className='text-[20px] font-medium'>Service Providers</span>
            <span className='text-[20px] font-medium'> - </span>
            <span>
              Providing services on OHM platform such as a) Lenders including
              bank, NBFCs and such other institutions in the business of
              lending, and b) Goods and Service Providers.
            </span>
          </div>
          <div className='paragraph mt-[10px] mb-[10px] items-center px-2'>
            <span className='text-[20px] font-medium'>Marketplace</span>
            <span className='text-[20px] font-medium'> - </span>
            <span>
              Specific areas in website/Mobile applications for buying Goods and
              Services
            </span>
          </div>
          <div className='next-paragraph  px-2'>
            <p>
              For the purpose of these Terms of Use, wherever the context so
              requires You or User shall mean any natural or legal person who
              has agreed to become a user or buyer on the Website by providing
              Registration Data while registering on the Website as Registered
              User using the computer systems. Users are also allowed to surf
              the Website without registering on the Website.
            </p>
          </div>
          <div className='next-line  px-2'>
            <p>
              The term We, Us, Our, “Platform”, “OHM” shall mean OHM Platform.
            </p>
          </div>
          <div className='second-header mt-[15px] mb-[15px]'>
            <h2 className='font-roboto text-[20px] text-gray-800'>
              Terms of Use
            </h2>
          </div>
          <div className='next-paragraph  px-2'>
            <p>
              For the purpose of these Terms of Use, wherever the context so
              requires You or User shall mean any natural or legal person who
              has agreed to become a user or buyer on the Website by providing
              Registration Data while registering on the Website as Registered
              User using the computer systems. Users are also allowed to surf
              the Website without registering on the Website.
            </p>
          </div>
          <div className='next-paragraph  mt-[20px] px-2'>
            <p>
              www.OHM.com is a platform that facilitates Users to meet and
              interact with one another for their transactions. OHM is not and
              cannot be a party to or control in any manner any transaction
              between the Platform Users.
            </p>
          </div>
          <div className='third-header mt-[10px]'>
            <h2 className='text-[24px] text-[#2d3748]'>General information</h2>
            <div className='w-24 border-b-2 border-green-400' />
          </div>
          <div className='paragraph mt-[10px] mb-[10px]  items-center px-2'>
            <div>
              {' '}
              <div>
                <span>a.</span> You are requested to read SRTOU for the
                following:
              </div>
              <div className='ml-[15px]'>
                i. Granting acceptance to these presents;
              </div>
              <div className='ml-[15px]'>
                ii. Use OHM website with/without creating/signing in to your
                User Account as provided.
              </div>
              <div className='ml-[15px]'>
                iii. For creating User Account on the OHM Platform;
              </div>
              <div className='ml-[15px]'>
                iv. For transacting on the e-marketplace platform buying goods
                and services from Service Providers.
              </div>
              <div className='ml-[15px]'>
                v. For making loan applications to Lending Partners.
              </div>
            </div>
          </div>
          <div className='paragraph mt-[10px] mb-[10px]  items-center px-2'>
            <div>
              {' '}
              <div>
                <span>b.</span> It is also informed that the User Account shall
                be subject to the terms of these presents. In case you disagree,
                you shall not use the OHM Platform and its services. You shall
                leave the OHM Platform before acceptance of these terms or use
                of the OHM Platform.
              </div>
            </div>
          </div>
          <div className='paragraph mt-[10px] mb-[10px]  items-center px-2'>
            <div>
              {' '}
              <div>
                <span>c.</span>OHM Platform’s General Terms and Conditions,
                Privacy Policy, Disclaimers, Other Policies applicable in
                general, and/or to specific areas of OHM Platform are also
                considered part of this SRTOU. The aforesaid is incorporated
                herein by way of reference, which shall be noted by you or any
                persons acting for you from time to time.
              </div>
            </div>
          </div>
          <div className='paragraph mt-[10px] mb-[10px]  items-center px-2'>
            <div>
              {' '}
              <div>
                <span>d.</span>By accepting these terms, you further confirm
                that your use of the OHM Platform shall be subject to compliance
                with the OHM Platform General Terms and Conditions, Privacy
                Policy, Disclaimers, Other Policies applicable in general.
              </div>
            </div>
          </div>
          <div className='paragraph mt-[10px] mb-[10px]  items-center px-2'>
            <div>
              {' '}
              <div>
                <span>e.</span>The use of OHM Platform shall constitute a valid
                and binding legal contract between you, Service Provider and OHM
                Platform concerning this SRTOU and other terms incorporated by
                way of the reference here.
              </div>
            </div>
          </div>
          <div className='paragraph mt-[10px] mb-[10px]  items-center px-2'>
            <div>
              {' '}
              <div>
                <span>f.</span>By using the OHM Platform, you acknowledge and
                confirm that you have read, understood and bound by the terms
                mentioned in this document.
              </div>
            </div>
          </div>
          <div className='paragraph mt-[10px] mb-[10px]  items-center px-2'>
            <div>
              {' '}
              <div>
                <span>g.</span>You are informed that your right to use the OHM
                Platform can be denied at any point in time without any prior
                intimation, and you confirm the same.
              </div>
            </div>
          </div>
          <div className='paragraph mt-[10px] mb-[10px]  items-center px-2'>
            <div>
              {' '}
              <div>
                <span>h.</span>You are also informed that you shall re-visit the
                SRTOU from time to time to stay abreast of any changes that the
                OHM Platform may introduce. The OHM Platform reserves the right
                to modify the SRTOU at any time without giving you any prior
                notice. Any updates concerning such modifications shall be
                available only in the OHM Platform, and such changes shall be
                binding on you
              </div>
            </div>
          </div>
          <div className='paragraph mt-[10px] mb-[10px]  items-center px-2'>
            <div>
              {' '}
              <div>
                <span>i.</span>You confirm that you satisfy the criteria
                prescribed under applicable laws, to enter into a contract and
                have legal competence and capacity. Also, you have requisite
                authority from the organization to get the work and payment
                thereof to Service Providers
              </div>
            </div>
          </div>
          <div className='paragraph mt-[10px] mb-[10px]  items-center px-2'>
            <div>
              {' '}
              <div>
                <span>j.</span>OHM Platform may translate these Terms into other
                languages for convenience. Nevertheless, the English version
                governs the relationship with OHM Platform, and any
                inconsistencies among the different versions will be resolved in
                favor of the English version.
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default index;
